import { Poppins } from 'next/font/google';
import './globals.css';
import { NextUiproviders } from '@/providers/nextUi/nextUiProvider';
import { ThemeProviders } from '@/providers/darkTheme/themeProvider';
import Header from '@/components/Header'


const inter = Poppins({weight: '400', subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=''>
      <body className={inter.className}>
        <NextUiproviders>
          <ThemeProviders>
          <Header/>
           {children}
          </ThemeProviders>
        </NextUiproviders>
      </body>
    </html>
  )
}
